### ISSUE TITLE
Unable to download .zip file of my app

### ISSUE THREAD

**Issue by Abhishek-Choudharyy** [wit-ai/wit#1173]
My app id : 5ae1885f-0c24-461f-b535-5aedca248d8c, I a

I want to make a clone of this app and add some new entities to that cloned app. But I am unable to download the .zip file of this app.

Error :
{
    error: "Something went wrong. W.'ve been notified.",
    code: "wit"
}

Please let me know how to clone an app

**Comment by jackneil** [comment]
Same issue here.

**Comment by stopachka** [comment]
Hey @Abhishek-Choudharyy  @jackneil 

--- 

Please include your app-ids. I would also advise against sharing the private handle (that will make it possible for others to download your app)

**Comment by jackneil** [comment]
Looks like it is fixed now. Thank you

**Comment by jtliao** [comment]
hi @Abhishek-Choudharyy, are you still experiencing this issue?

**Comment by Abhishek-Choudharyy** [comment]
@jtliao yes still the same issue, My app id : 5ae1885f-0c24-461f-b535-5aedca248d8c. please check

**Comment by jtliao** [comment]
Hi @Abhishek-Choudharyy, I'm still having trouble reproducing this bug, exporting your app seems to be working for me. To make sure we're on the same page, are you just clicking the "Download .zip with your data" button on the settings page? If so, can you just try refreshing the settings page before trying to download (we're experiencing another bug regarding the Settings page, probably unrelated but worth a shot). 

If none of these help, please provide any other info you may see when trying to export your app (other errors in logs, console, etc.) and we'll try to figure out the issue.

**Comment by Abhishek-Choudharyy** [comment]
Hello @jtliao,  I can't test the issue right now as I am unable to login via facebook.

![screenshot from 2018-08-16 11-39-17](https://user-images.githubusercontent.com/29659840/44191452-2cbbf480-a149-11e8-80a5-68fa4db9ef41.png)

**Comment by vcnsiqueira** [comment]
Same issue here. App id: 
1808172539205079180817

**Comment by jtliao** [comment]
I'm able to reproduce now, looking into the root cause and will look to have a fix out.

**Comment by vcnsiqueira** [comment]
any solution to this issue? Still can't download the zip of my data.

**Comment by Abhishek-Choudharyy** [comment]
@jtliao Thanks, I am able to export successfully.

**Comment by h2media** [comment]
AppID : 58b77c2f-096d-4779-bc18-10a47e89378b

the same issue :(  @jtliao pls help me download zip

**Comment by jtliao** [comment]
@h2media should be fixed now
