### ISSUE TITLE
Unable to export

### ISSUE THREAD

**Issue by jefferyhayes** [wit-ai/wit#1712]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Potential bug

**What is the current behavior?**
On the app settings page, I cannot export/download app data

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1 - Click "Download .zip with your data", 
2 - Get error "Something went wrong while exporting your app 😣. Please try again, or contact us."

![image](https://user-images.githubusercontent.com/2111685/80814083-186b9580-8b80-11ea-9dfe-c2abf1db5f24.png)

**What is the expected behavior?**
1 - click "Download .zip with your data"
2 - .zip downloads

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2464252626970124

**Comment by jtliao** [comment]
sorry about that, this should be fixed now

**Comment by jefferyhayes** [comment]
Hello - I am still getting this error when trying to export from the website or via the API.
