### ISSUE TITLE
Uterrances page is empty

### ISSUE THREAD

**Issue by asfyra** [wit-ai/wit#1951]
I think there is a problem with the utterances page for appId: 2841817995840539
When i click the utterances link on the menu i get the following:

![image](https://user-images.githubusercontent.com/6898230/97583448-a3c6c600-19ff-11eb-856f-26609d7d7c52.png)

It does not load anything even if i try to add any filter on the search text box above.
Could you please check if there is something wrong with our app.

Thank you
Alex

**Comment by jtliao** [comment]
fixed

**Comment by asfyra** [comment]
Hello @jtliao it's not fixed. All the traits of the application are gone !
We are unable to perform further trainig as all the traits we had built over time disappeard.
I tried to get a backup but backup does not work
The application had one intent and handrends of traits. Now only the one intent is present.
At the moment the bot that is uing this app responds but i am affraid after the training finishes, it will stop responding

Can you please restore the traits of the application ? 

Thank you
Alex

**Comment by asfyra** [comment]
@jtliao  Everything is back, utterances page is fully functional
Thanks a lot for your help !
