### ISSUE TITLE
Export data is not working: Something went wrong. We've been notified

### ISSUE THREAD

**Issue by serdalbayram** [wit-ai/wit#2010]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Exporting data is not working, it gives following error: **Something went wrong. We've been notified**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
After clicking "Download .zip with your data" button under "Export Your Data" part, the error message is displaying.

**What is the expected behavior?**
Download zip file.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1622020321212473

**Comment by dupengling** [comment]
Hi @serdalbayram 

Thanks for reporting. We've fixed the app on the backend. Let me know if you have any other questions.

**Comment by serdalbayram** [comment]
Thank you @dupengling , but the problem is still not solved :(  The same problem is faced. Could you please check it again?

**Comment by dupengling** [comment]
Can you try it again? It seems my last fix wasn't proceed. Now it should be good.

**Comment by serdalbayram** [comment]
Now it is working, thank you :)
