### ISSUE TITLE
Wit.ai internal server error

### ISSUE THREAD

**Issue by kevinjon27** [wit-ai/wit#2095]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**<img width="1440" alt="Screen Shot 2021-05-28 at 12 33 16" src="https://user-images.githubusercontent.com/12078441/119935262-69cb9b80-bfb1-11eb-965c-947a0566c862.png">BUG

**What is the current behavior?**
My wit.ai on bot not respon anything, when I check on wit.ai website and I think the server error, because I see internal server error when I trying to input on understanding feature

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

<img width="1440" alt="Screen Shot 2021-05-28 at 12 33 16" src="https://user-images.githubusercontent.com/12078441/119935262-69cb9b80-bfb1-11eb-965c-947a0566c862.png">**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
APP ID= 365518614749604

**Comment by kevinjon27** [comment]
Hello, need help because we have a deadline for this project. And our project broken because this issue

**Comment by kevinjon27** [comment]
need support for this guys. we use wit.ai for production apps and now our app is broken.

**Comment by kevinjon27** [comment]
<img width="1002" alt="Screen Shot 2021-05-31 at 22 00 13" src="https://user-images.githubusercontent.com/12078441/120212141-d8cc1d00-c25b-11eb-8067-6ad7f3292079.png">

**Comment by chessai** [comment]
@kevinjon27 I deleted your most recent message because your token was improperly obscured. Please do a better job of obscuring sensitive information before posting anything.

**Comment by kevinjon27** [comment]
any updates?

**Comment by chessai** [comment]
See https://github.com/wit-ai/wit/issues/2105#issuecomment-856296095

**Comment by chessai** [comment]
This should be resolved. See https://github.com/wit-ai/wit/issues/2105#issuecomment-860916172

**Comment by kevinjon27** [comment]
@chessai hi bro, our train dashboard still not working.

<img width="1440" alt="Screen Shot 2021-06-15 at 09 52 28" src="https://user-images.githubusercontent.com/12078441/121985746-90fed700-cdbf-11eb-83f6-6b9f285443e3.png">

**Comment by kevinjon27** [comment]
the API not working @chessai 

<img width="1025" alt="Screen Shot 2021-06-15 at 09 56 52" src="https://user-images.githubusercontent.com/12078441/121986047-14b8c380-cdc0-11eb-9dc7-d79b6ad67959.png">
