### ISSUE TITLE
Apps not loading 

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#2110]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Live phrases aren't coming through the app and wit pre-built entities aren't picking up 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1498980583476446

**Comment by nickcbarone** [comment]
We are experiencing the same issue.

**Comment by kevinjon27** [comment]
Me too

**Comment by patapizza** [comment]
This has been resolved.

**Comment by nickcbarone** [comment]
This is not resolved. https://github.com/wit-ai/wit/issues/2122
