### ISSUE TITLE
Working apps stopped working with Bad auth error response for token (400 bad request)

### ISSUE THREAD

**Issue by mohammad-melhem** [wit-ai/wit#2234]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
API calling is not working and we get the following error on apps that were working normally for a while:
- HTTP resp status: 400 Bad request
- Response body:
{
    "error": "Bad auth, check token/params",
    "code": "no-auth"
}

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
calling the same API with the same server token that has been working for a long while suddenly returns the above error.

**What is the expected behavior?**
Should work normally without generating a new token.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
Multiple apps.

Note: seems other issues also relate to the same cause, so it looks that it might be on platform level.

Thanks for your cooperation in advance.

**Comment by b-tix** [comment]
Same problem to us with App ID 2115985458480186.

**Comment by DegtiarDmitro** [comment]
We have the same problem (App ID: 2654426877976507).

**Comment by Santhosh3006** [comment]
I also Same Problem

**Comment by sebastianarena** [comment]
+1 with a multitude of apps... so far more than 15 of the ones we manage
Regenerating the Server Token fixes the issue

**Comment by 91ns** [comment]
We're having the same issue and UI doesn't open so we're not able to reset the tokens 
APP ID 204584064787119

**Comment by francescor93** [comment]
I confirm both that I encountered the same problem, and that I solved it by refreshing my token. So I seem to understand that all existing tokens have been revoked, looking forward for the team to explain us if something went wrong.

**Comment by mohansr03** [comment]
Same problem for me as well

**Comment by 465730396** [comment]
We have the same problem (App ID: 275869200134768).
We have the same problem (App ID: 482075939147009).

**Comment by 465730396** [comment]
anybody fix it？

**Comment by zoirs** [comment]
I have the same problem. App ID: 383297309768429

**Comment by abhilashmurthy** [comment]
Same problem guys. Many of our enterprise clients depend on Wit. Please do fix this as soon as possible

**Comment by sophiexr** [comment]
we have the same issue. App 2841817995840539

thanks

**Comment by admin-pulsar** [comment]
HHello, We have the same problem, App ID is 1450216708378959, getting error: Bad auth, check token/params" code: "no-auth"

**Comment by Romerito007** [comment]
Same code problem: "no-auth" here, I can't access my application area. Does not load https://wit.ai/apps

**Comment by mohammad-melhem** [comment]
A quick comment as the problem seems to affect more and more apps, so as others suggested before, the current fix is to regenerate the access token from the app settings (if you are able to access the app settings through UI, cause unfortunately, it looks like some apps are not accessible through the website as well).

**Comment by admin-pulsar** [comment]
Regenerate access token doesn't help, We tried it but no result :(

**Comment by mohammad-melhem** [comment]
mmm that's weird .. I've tried it with many apps and tested with postman using the newly regenerated token and it worked, so I updated the token in my server apps and they started working normally again. Well, hope they get to fix/explain very soon since even using a regenerated token is not working for some apps.

**Comment by Romerito007** [comment]
> Same code problem: "no-auth" here, I can't access my application area. Does not load https://wit.ai/apps

I solved my access by creating a new account, logging in with my facebook it loaded all my applications I generate a new token, now everything works

**Comment by lycai-fb** [comment]
Thanks for all the reports. We're investigating the issue.

**Comment by lycai-fb** [comment]
Hi all,
Regenerating server token and changing your call sites to use the new token appears to work for most cases.
For those who are unable to access their app page or have tried regenerating and still doesn't work, could you provide your App IDs please?

**Comment by lycai-fb** [comment]
Hi all,

We found that some server tokens were mistakenly removed from the backend. We will be performing a backfill job over the next few hours to restore the data.
If you haven't regenerated your server token, then it should start working again after the backfill. If you have, it should still work just make sure you are using your updated server token.
We will initially be backfilling server tokens for the app **owners**. If you are using a **contributor** server token, consider switching to the one for the app **owner**.

Please comment if you are still having issues and include your app id.

**Comment by r-alnairab** [comment]
Apps:
1633145430167212
428511981337261


api.wit.ai/message?v=20190101

We are still facing the same issue. 
`{
   "error": "Bad auth, check token/params",
   "code": "no-auth"
}`

We are also not able to login to wit.ai/app

**Comment by sophiexr** [comment]
we're still having an issue App 2841817995840539
thanks

**Comment by lmessinger** [comment]
we're still having the issue, app 181514110593962

**Comment by r-alnairab** [comment]
We have 4 App IDs:
424776275488729
1050818978949445
1633145430167212
428511981337261

**Comment by arsantos77** [comment]
I don't know my ID, just the URL:

https://api.wit.ai/speech?v=20200513

**Comment by felippebueno** [comment]
I have over 300 APPS with similar issues. I can't even generate new tokens, a screen goes blank when I click regenerate!

**Comment by r-alnairab** [comment]
We were able to login to our wit.ai account **after trying many times**.
We re-generated the API Token and replaced them in our chatbots, and they worked fine.

**Comment by ankvietnx4** [comment]
I'm having the issue but it is with the client token
Regenerate work well but I have 20 apps so it is very inconvenient to do that with such apps
Looking forward for the team to fixing the bug.
Thanks

**Comment by admin-pulsar** [comment]
Hello, After regenerating server token, It started work, it was on Friday evening, Now I've checked and the same problem occurred again :( App ID is 1450216708378959.

**Comment by serdalbayram** [comment]
I can't login wit.ai/app, listing apps is not working, so I can't regenerate the tokens, many applications are depending on this service. Looking forward to the team fixing the bug.

**Comment by nickcbarone** [comment]
I can't login to wit.ai/app. Same as @serdalbayram. My wit apps are also still not working. When will this be fixed? Like @ankvietnx4 , we have over 20 apps. To change their API token would be extremely inconvenient. Please fix this bug asap.

**Comment by anjaly** [comment]
We are also experiencing the same issue. Two days back we had generated new tokens and updated in all chatbots for fixing the Bad AUTH issue and it worked.
But now we are unable to sign in to our account. Please help.
Also the status page is not loading https://wit.ai/status

**Comment by jacobilin** [comment]
The same problem for us.

**Comment by GauravDobhal** [comment]
Same with us. We also regenerated all the tokens a couple of days ago after the initial bad token error

**Comment by backmeupplz** [comment]
@lycai-fb can't see my apps ids because I can't login with Facebook :( my account is backmeupplz@gmail.com, can we fix it?

**Comment by blue7080** [comment]
> **آیا می خواهید یک _ویژگی_ را درخواست کنید ، یک _اشکال را_ گزارش کنید یا _در_ مورد شوخ طبعی سؤالی بپرسید ؟ ** حشره
> 
> **رفتار فعلی چیست؟ ** فراخوانی API کار نمی کند و در برنامه هایی که مدتی به طور معمول کار می کردند با خطای زیر مواجه می شویم:
> 
> * وضعیت پاسخ HTTP: 400 درخواست بد
> * بدنه پاسخ: 
>   { 
>   "خطا": "Auth بد، علامت/پارام ها را بررسی کنید"، 
>   "code": "no-ath" 
>   }
> 
> **اگر رفتار فعلی یک اشکال است، لطفاً مراحل بازتولید و در صورت امکان حداقل نسخه نمایشی مشکل را ارائه دهید. ** فراخوانی همان API با همان توکن سرور که برای مدت طولانی کار کرده است، ناگهان خطای بالا را برمی گرداند.
> 
> **رفتار مورد انتظار چیست؟ ** باید به طور معمول بدون ایجاد توکن جدید کار کند.
> 
> **در صورت وجود، شناسه برنامه که در آن با این مشکل مواجه هستید چیست؟ اگر شما این را ارائه نکنید، ما نمی توانیم کمک کنیم. ** برنامه های متعدد
> 
> توجه: به نظر می رسد مسائل دیگر نیز به همین علت مربوط می شود، بنابراین به نظر می رسد که ممکن است در سطح پلت فرم باشد.
> 
> پیشاپیش از همکاری شما سپاسگزاریم

I still have a problem

**Comment by blue7080** [comment]
> **Do you want to request a _feature_, report a _bug_, or ask a _question_ about wit?** bug
> 
> **What is the current behavior?** API calling is not working and we get the following error on apps that were working normally for a while:
> 
> * HTTP resp status: 400 Bad request
> * Response body:
>   {
>   "error": "Bad auth, check token/params",
>   "code": "no-auth"
>   }
> 
> **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** calling the same API with the same server token that has been working for a long while suddenly returns the above error.
> 
> **What is the expected behavior?** Should work normally without generating a new token.
> 
> **If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.** Multiple apps.
> 
> Note: seems other issues also relate to the same cause, so it looks that it might be on platform level.
> 
> Thanks for your cooperation in advance.

I still have a problem

**Comment by lycai-fb** [comment]
Hi all,

We have backfilled owner token for most affected apps. For example, @r-alnairab, @admin-pulsar, @lmessinger and @sophiexr your apps should be working if used with the owner token. Please comment if this is not the case.

We are currently investigating the reports of users not being to log in. If you are currently experiencing either issue, please comment with your app ID or username / email and we will look into your particular case as well.

**Comment by CannonFodderr** [comment]
@lycai-fb still having issues with account temi.production@gmail.com

**Comment by lycai-fb** [comment]
Update: We've found the login issue and are currently deploying a fix. Thanks for your patience.

**Comment by jacobilin** [comment]
854153648327148 doesn't work.

**Comment by lycai-fb** [comment]
Hi @jacob-i. I tested your app with owner server token ending in **QCI. It seems to work fine for me.
We plan to backfill user server tokens in the near future.

**Comment by CannonFodderr** [comment]
@lycai-fb Tested now with temi.production@gmail.com seems like we are able to create apps with the token but not to delete apps or generate new intents.

**Comment by jacobilin** [comment]
> Hi @jacob-i. I tested your app with owner server token ending in **QCI. It seems to work fine for me. We plan to backfill user server tokens in the near future.

We're using "Client Access Token" ending '...GAV' in production now. Would it be possible to make it work with this token?

**Comment by georgiep** [comment]
@lycai-fb We also have issues with account soul_mecca@yahoo.co.uk and token ending in ***LKR thank you

**Comment by backmeupplz** [comment]
@lycai-fb not sure if you've already deployed a fix for the fb login, but I still can't login to backmeupplz@gmail.com :(

**Comment by lycai-fb** [comment]
@jacob-i We will take longer to restore client tokens. I've restored yours ending in **GAV for the time being.

@backmeupplz The login fix will need some more time to deploy.

For others who are still getting errors with their tokens and cannot easily regenerate them, please provide your app id.
Thank you for your patience.

**Comment by jacobilin** [comment]
@lycai-fb it started working again. Thank you!

**Comment by backmeupplz** [comment]
Resolved on my end as well, thank you. Had to re-roll tokens on a few apps but that’s a no issue :)

**Comment by amtdevops** [comment]
> We are also experiencing the same issue. Two days back we had generated new tokens and updated in all chatbots for fixing the Bad AUTH issue and it worked. But now we are unable to sign in to our account. Please help. Also the status page is not loading https://wit.ai/status

Thanks @lycai-fb we are now able to login to our wit account.

**Comment by pa-lem** [comment]
@lycai-fb we have a lot of issues in a production environment 

**server tokens are inexplicably refreshing**

the first time, we updated all the tokens in our apps, but it started to fail again

so we **manually refreshed all the server tokens** that were failing, but it started again to fail

now, all the tokens are **again refreshed**, without any notice

we are currently refreshing and updating again all the tokens in our apps according to the tokens that are newly updated

is it possible to not update tokens anymore and make it work as it is ?

our app ids:
 
- 871633106762558
- 586773152331141
- 150922740301430
- 1443767085665352
- 534839584185995
- 1154503718388969
- 2141269122596313
- 4354831807883291
- 2059103737486184
- 1413941952002383
- 1519847294715571
- 1499231150138762
- 1453847548042462

thank you for your time

**Comment by lycai-fb** [comment]
Hi @pa-lem your tokens should not be refreshing by themselves unless you or a contributor refreshes it manually in settings. The fix that we are currently rolling out will make existing tokens work again without changing what is there.

I've manually fixed the few of your apps that have not been backfilled yet, e.g. 1443767085665352 and 4354831807883291. They should all be working now.

**Comment by yuzh174** [comment]
The fix was applied successfully. Your tokens should be working now. Let us know if you still see problems. Sorry for the inconvenience.

**Comment by yuzh174** [comment]
We have checked some of the apps reported here. They look good now. Please let us know if you still experience token failures.

**Comment by darshanamadlani** [comment]
> 

Hi,
I am having the same problem with my app ID 287425183206431.
Can you please check and help us with this?
