### ISSUE TITLE
Intermittent Internal Server Error 

### ISSUE THREAD

**Issue by llauv** [wit-ai/wit#2358]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
We are seeing intermittent "Internal Server Error" using https://api.wit.ai/message.  We've seen more of these errors starting 2/14/22.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 1937503576312674

**Comment by wangzhenict** [comment]
Hi @llauv ,
I met model cache issue at that time, it has been addressed. please let us know if you saw it again.

**Comment by llauv** [comment]
We are still seeing this error this morning at 10:07am (central time).

Lorena



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
