### ISSUE TITLE
[Very Urgent] Delayed intent training

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2526]
Hi,

Intent training is taking more than 30 minutes to 1h in all apps for past 2 weeks. This is creating issue with our clients. Sometimes it is getting scheduled to a later time after 2-5 hours.

@doggeral  Can some one please check and fix the issue ASAP.

This is not specific for any apps, all apps are facing this issue.

Thanks

**Comment by ChrisyShine** [comment]
The training taking too long problem should have been resolved. 
And the scheduling delay is expected. We have a scheduler to manage all the training tasks, so 2-5 hours are expected.

**Comment by anjaly** [comment]
> o 2-5 hours

@ChrisyShine the following App ID 397837775835719 is still showing ongoing training.
