### ISSUE TITLE
[URGENT] wit.ai message api is not working

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2768]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
Message Api is returning error for multiple wit.ai apps.
"https://api.wit.ai/message?q=Hi" is returning "503 Service Unavailable" error .

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Several of our clients have reported that the bot has stopped functioning.

**What is the expected behavior?**
Nothing has been changed from our side. So all the workspaces should work.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
APPID: 363040778909543

Please provide a solution as soon as possible, as the bots are currently not functioning.

**Comment by halemrani1996** [comment]
also for me in my apps i got wrong intents my apps ids 1920151674738030,1850539691729312
please support us please

**Comment by crazyrabbit0** [comment]
We had the same problem: **"503 Service Unavailable"**...

We fixed it by regenerating our API authentication keys  _(Server Access Token)_.

Turns out, our keys did not work from our online server, but worked fine locally for some reason _(probably IP related)_.

**Comment by anjaly** [comment]
@patapizza  Can it get fixed in meta side itself without regenerating the token.

**Comment by halemrani1996** [comment]
still got 503 Service Unavailable
on my english app id :1850539691729312
please support

**Comment by crazyrabbit0** [comment]
It's not completely fixed after all, 503 error messages still come in, but not on every request, it's seemingly random

**Comment by idanadut** [comment]
Same here.
@patapizza any update?

**Comment by alexjadame** [comment]
I have the same issue... we need some fix asap.

**Comment by CleanestMink126** [comment]
See #2767
