### ISSUE TITLE
Entity is not found from a large set of values

### ISSUE THREAD

**Issue by klemensz** [wit-ai/wit#548]
**Bug / Question**

I have an entity, let's call it "person", with something like 5000 values that I imported using the API. If I train the app "Tell me about John Doe" and mark John Doe as one of the person values, it will work. If I then try "Tell me about Mark Spencer" it won't recognize the name, although it's one of the values. Basically it means I would need to train each of the 5000 values once for it to work.

Also, if I type just "John Doe", it will be recognized, but not "Mark Spencer".

Expected behaviour: It should also recognize Mark Spencer as a person entity.

I can give private access to the app.

**Comment by patapizza** [comment]
Hi @klemensz,

What is the app id?

**Comment by klemensz** [comment]
It's 590c3891-b23b-4cb4-b5a2-c3cd0ef17397
The entity I'm testing with is actually called "player".

**Comment by patapizza** [comment]
Thank you @klemensz, this is indeed a bug. I'll look at it.

**Comment by patapizza** [comment]
Update: root cause fixed, still need to backfill -- will do tomorrow.

**Comment by patapizza** [comment]
@klemensz Thanks for your patience, this should be fixed now.

**Comment by klemensz** [comment]
Hi,
thanks. It works now with this app, but with another app we still have the issue with another app (5902737c-e922-4695-bed3-874f70abb502) that we created at the same time.

**Comment by patapizza** [comment]
Will fix on Monday.

**Comment by patapizza** [comment]
@klemensz done

**Comment by klemensz** [comment]
We re-imported the entities via the API in a batch and now we have the same issue again. Can you look into it?
