### ISSUE TITLE
wit/number is not returning numbers in entities in Ukrainian

### ISSUE THREAD

**Issue by XY-Wang** [wit-ai/wit#839]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
The number is not being returned in the list of entities in Ukrainian agent. I trained examples like "100 eur в uah" as an example with "100" and "eur" as a composite entities under the entity unitCurrency but the API only returns currency with value "EUR" but not the number. I also tried training examples with only a number like "100" but the API is also not returning any number entity. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

![screen shot 2017-10-30 at 5 29 36 pm](https://user-images.githubusercontent.com/17497561/32182863-0041184e-bd98-11e7-9f94-e67cda0fb3a6.png)

![screen shot 2017-10-30 at 5 30 06 pm](https://user-images.githubusercontent.com/17497561/32182867-027e64fe-bd98-11e7-89e3-38c6dc6e460e.png)

**What is the expected behavior?**
There should be a field in entities with the extracted value of the number. 

```
[
  {
    "confidence": null,
    "intent": "default_intent",
    "_text": "100",
    "entities": {
      "number": [
        {
          "confidence": 1,
          "value": 100,
          "type": "value"
        }
      ],
      "intent": [
        {
          "confidence": 0.89783027984225,
          "value": "complete_number"
        }
      ]
    }
  }
]
```

**What is the App ID where you are experiencing this issue (if applicable)?**
59f05f84-7c54-4463-a779-970c490ff2eb

**Comment by patapizza** [comment]
@XY-Wang Wit relies on [Duckling](https://github.com/facebook/duckling) for `wit/number` and `wit/amount-of-money`. Feel free to make a pull request if you have some time!

**Comment by XY-Wang** [comment]
@patapizza I saw in Duckling that there is Ukrainian support for numerals. It's in the new version of Duckling (facebookincubator/duckling) Is this the version used in wit.ai right now?

**Comment by XY-Wang** [comment]
@patapizza My tests in Duckling seem to be working perfectly but the same text in wit.ai is not resolving :( 

```        
➜  ~ curl -XPOST http://0.0.0.0:8000/parse --data 'locale=uk_UK&text=100'
[{"dim":"number","body":"100","value":{"value":100,"type":"value"},"start":0,"end":3}]%                                                                                                                    
➜  ~ curl -XPOST http://0.0.0.0:8000/parse --data 'locale=uk_UK&text=двісті сімдесят вісім'
[{"dim":"number","body":"двісті сімдесят вісім","value":{"value":278,"type":"value"},"start":0,"end":21}]%
```

**Comment by blandinw** [comment]
uk_UK is not a locale, did you mean en_GB?

**Comment by blandinw** [comment]
I'll look into it.

**Comment by blandinw** [comment]
@XY-Wang Duckling thought your app was set to English, I made sure it is now set to Ukrainian. This is a known temporary issue on our side and due to our migration to more robust infra. We're working on a proper fix. 

Thanks again for reporting!

**Comment by XY-Wang** [comment]
@blandinw Hi! I've noticed recently that the numbers are not resolving again :( I know that wit.ai has been doing some update/migration. Could you please help to check if the old issue is happening again?

Thanks!

**Comment by blandinw** [comment]
@XY-Wang your app looks good, the old issue is not happening again. (id 59f05f84-7c54-4463-a779-970c490ff2eb).
Are you still experiencing issues?

**Comment by XY-Wang** [comment]
@blandinw I tested after you fixed it the other time and it was working but now it's not returning the number entity again, same as before. Here's the screenshot of one of the utterances I was trying to train with wit/numbers:

![screen shot 2017-11-28 at 9 59 52 am](https://user-images.githubusercontent.com/17497561/33310739-e9d83712-d422-11e7-827a-a56968fa7588.png)

**Comment by stopachka** [comment]
Confirmed, indeed the number is not returning. Will look into this further and update here

**Comment by blandinw** [comment]
@XY-Wang thank you for pushing on this issue.
`wit/number` in Ukrainian was in a broken state, I fixed it and am taking steps so that it does not happen again.
Everything should be working as expected now, closing.

**Comment by XY-Wang** [comment]
@blandinw Hi! Thanks for looking into this but I still don't see the number returning :( Do I have to retrain my agent for it to work?

**Comment by blandinw** [comment]
@XY-Wang I found the root cause and will fix it tomorrow. You won't have to do anything on your end! Thank you for the feedback.

**Comment by blandinw** [comment]
This bug was fixed last week for all apps
