### ISSUE TITLE
I am getting "Network is unreachable" error when pinging wit.ai from my messenger bot

### ISSUE THREAD

**Issue by fr1sk** [wit-ai/wit#885]
Hi, today I experienced this error

`ConnectionError: HTTPSConnectionPool(host='api.wit.ai', port=443): Max retries exceeded with url: /message?q=hej (Caused by <class 'socket.error'>: [Errno 101] Network is unreachable)`

any ideas whats wrong? Maybe some problems on my side?

**Comment by stuartd** [comment]
Seeing lots of problems today - timeouts calling the service, and just now https://wit.ai/ was down

**Comment by hactar** [comment]
Confirmed - getting timeouts when calling the /message api.

**Comment by rowanvanekeren** [comment]
confirmed here aswell

**Comment by domsammut** [comment]
Confirmed. Had multiple periods of 502 over the last 12 hours.

**Comment by l5t** [comment]
Thanks for reporting. We are investigating

**Comment by dennisaskeland** [comment]
Same issue with no connection from Wit..

**Comment by patapizza** [comment]
Are you guys still experiencing the issue? Is this consistent?

**Comment by stuartd** [comment]
https://api.wit.ai is working for me now

**Comment by dennisaskeland** [comment]
@patapizza yes - or well, it's on and off. We have a few minutes of working service, and then we have time outs for a few minutes, and so on

**Comment by patapizza** [comment]
Thanks, we're on it.

**Comment by hweiler** [comment]
We are also experiencing intermittent issues with our apps. Sometimes it will work as expected and other times the response will time out.

**Comment by llorimier** [comment]
@patapizza Hi, still strongly impacted as well. Ready to help you investigating if needed. Thanks !

**Comment by otnorli** [comment]
have been experiencing issues the last 14 hours approximatly. hoping for fix

**Comment by patapizza** [comment]
It should be resolved now. Can someone confirm?

**Comment by moberemk** [comment]
No error reports from our end in the past hour and it seems reachable from our server cluster. Looks better to me?

**Comment by akapei** [comment]
I'm still getting the timeout errors.

This a couple of minutes ago:
Error: request to https://api.wit.ai/message?q=... failed, reason: connect ETIMEDOUT 66.220...

**Comment by blandinw** [comment]
@akapei how often are you getting timeouts? This is likely a different issue since this thread is about a `Network unreachable` error.

**Comment by akapei** [comment]
@blandinw Should I open a separate issue? 

I first noticed it about a week ago. It seems to happen all the time. Some requests work fine then a bunch will timeout.
